import streamlit as st
import requests
API_KEY = "bbf0c93082d64c662dca0de9"
st.title("Currency Converter")
country_currency = {
'United States': 'USD',
'United Arab Emirates': 'AED',
'Afghanistan': 'AFN',
'Albania': 'ALL',
'Armenia': 'AMD',
'Netherlands Antilles': 'ANG',
'Angola': 'AOA',
'Argentina': 'ARS',
'Australia': 'AUD',
'Aruba': 'AWG',
'Azerbaijan': 'AZN',
'Bosnia and Herzegovina': 'BAM',
'Barbados': 'BBD',
'Bangladesh': 'BDT',
'Bulgaria': 'BGN',
'Bahrain': 'BHD',
'Burundi': 'BIF',
'Bermuda': 'BMD',
'Brunei': 'BND',
'Bolivia': 'BOB',
'Brazil': 'BRL',
'Bahamas': 'BSD',
'Bhutan': 'BTN',
'Botswana': 'BWP',
'Belarus': 'BYN',
'Belize': 'BZD',
'Canada': 'CAD',
'Democratic Republic of the Congo': 'CDF',
'Switzerland': 'CHF',
'Chile': 'CLP',
'China': 'CNY',
'Colombia': 'COP',
'Costa Rica': 'CRC',
'Cuba': 'CUP',
'Cabo Verde': 'CVE',
'Czech Republic': 'CZK',
'Djibouti': 'DJF',
'Denmark': 'DKK',
'Dominican Republic': 'DOP',
'Algeria': 'DZD',
'Egypt': 'EGP',
'Eritrea': 'ERN',
'Ethiopia': 'ETB',
'Eurozone': 'EUR',
'Fiji': 'FJD',
'Falkland Islands': 'FKP',
'United Kingdom': 'GBP',
'Georgia': 'GEL',
'Ghana': 'GHS',
'Gibraltar': 'GIP',
'Gambia': 'GMD',
'Guinea': 'GNF',
'Guatemala': 'GTQ',
'Guyana': 'GYD',
'Hong Kong': 'HKD',
'Honduras': 'HNL',
'Croatia': 'HRK',
'Haiti': 'HTG',
'Hungary': 'HUF',
'Indonesia': 'IDR',
'Israel': 'ILS',
'India': 'INR',
'Iraq': 'IQD',
'Iran': 'IRR',
'Iceland': 'ISK',
'Jamaica': 'JMD',
'Jordan': 'JOD',
'Japan': 'JPY',
'Kenya': 'KES',
'Kyrgyzstan': 'KGS',
'Cambodia': 'KHR',
'Comoros': 'KMF',
'South Korea': 'KRW',
'Kuwait': 'KWD',
'Cayman Islands': 'KYD',
'Kazakhstan': 'KZT',
'Laos': 'LAK',
'Lebanon': 'LBP',
'Sri Lanka': 'LKR',
'Liberia': 'LRD',
'Lesotho': 'LSL',
'Libya': 'LYD',
'Morocco': 'MAD',
'Moldova': 'MDL',
'Madagascar': 'MGA',
'North Macedonia': 'MKD',
'Myanmar': 'MMK',
'Mongolia': 'MNT',
'Macau': 'MOP',
'Mauritania': 'MRU',
'Mauritius': 'MUR',
'Maldives': 'MVR',
'Malawi': 'MWK',
'Mexico': 'MXN',
'Malaysia': 'MYR',
'Mozambique': 'MZN',
'Namibia': 'NAD',
'Nigeria': 'NGN',
'Nicaragua': 'NIO',
'Norway': 'NOK',
'Nepal': 'NPR',
'New Zealand': 'NZD',
'Oman': 'OMR',
'Panama': 'PAB',
'Peru': 'PEN',
'Papua New Guinea': 'PGK',
'Philippines': 'PHP',
'Pakistan': 'PKR',
'Poland': 'PLN',
'Paraguay': 'PYG',
'Qatar': 'QAR',
'Romania': 'RON',
'Serbia': 'RSD',
'Russia': 'RUB',
'Rwanda': 'RWF',
'Saudi Arabia': 'SAR',
'Solomon Islands': 'SBD',
'Seychelles': 'SCR',
'Sudan': 'SDG',
'Sweden': 'SEK',
'Singapore': 'SGD',
'Sierra Leone': 'SLE',
'Somalia': 'SOS',
'Suriname': 'SRD',
'South Sudan': 'SSP',
'Sao Tome and Principe': 'STN',
'Syria': 'SYP',
'Eswatini': 'SZL',
'Thailand': 'THB',
'Tajikistan': 'TJS',
'Turkmenistan': 'TMT',
'Tunisia': 'TND',
'Tonga': 'TOP',
'Turkey': 'TRY',
'Trinidad and Tobago': 'TTD',
'Taiwan': 'TWD',
'Tanzania': 'TZS',
'Ukraine': 'UAH',
'Uganda': 'UGX',
'Uruguay': 'UYU',
'Uzbekistan': 'UZS',
'Venezuela': 'VES',
'Vietnam': 'VND',
'Vanuatu': 'VUV',
'Samoa': 'WST',
'Central African CFA Zone': 'XAF',
'East Caribbean': 'XCD',
'West African CFA Zone': 'XOF',
'CFP Franc Zone': 'XPF',
'Yemen': 'YER',
'South Africa': 'ZAR',
'Zambia': 'ZMW',
'Zimbabwe': 'ZWL'
}
country_in=st.selectbox("Select Currency",list(country_currency.keys()))
base_currency=country_currency[country_in]
st.success(f"Base Currency: {base_currency}")
input_currency_amount = st.number_input("Input Amount")
st.success(f"Input Amount: {input_currency_amount}")
url = f"https://v6.exchangerate-api.com/v6/{API_KEY}/latest/{base_currency}"
response = requests.get(url)
data = response.json()
country_out=st.selectbox("Select Output Currency",list(country_currency.keys()))
base_currency_out=country_currency[country_out]
rate=data["conversion_rates"][base_currency_out]
st.success(f"Conversion Rate: {rate}")
output_currency=input_currency_amount*rate
st.success(f"Output Currency in {base_currency_out}: {output_currency}")



